---
title: "Data Manipulation"
author: "Sitruks"
date: "April 26, 2018"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(dplyr)
library(tidyr)
```

### Data Wrangling Exercise 1:  

#### Task 0
Load Data into RStudio
```{r}
refine <- tbl_df(read_csv("C:/Users/v-kursan/Downloads/Capstone_DS/Wrangle/1_Basic_Data_Manipulation/refine_original.csv"))
```


#### Tasks 1-5
```{r}

refine <- refine %>% 
           separate('Product code / number', into = c("product_code", "product_number")) %>% 
           mutate(companies = if_else(grepl("^p|^P|^f|^F", company), "philips",
                  if_else(grepl("^a|^A", company), "akzo",
                  if_else(grepl("^v|^V", company), "van houten",
                  if_else(grepl("^u|^U", company), "unilever",
                    "other")))),
                product_category = if_else(grepl("p", product_code), "smartphone",
                  if_else(grepl("v", product_code), "tv",
                  if_else(grepl("x", product_code), "laptop",
                  if_else(grepl("q", product_code), "tablet",
                    "other")))),
                full_address = paste(address, city, country, sep = ", "),
                company_philips = if_else(grepl("p", companies), 1 , 0),
                company_akzo = if_else(grepl("a", companies), 1, 0),
                company_van_houten = if_else(grepl("v", companies), 1, 0),
                company_unilever = if_else(grepl("u", companies), 1, 0),
                product_smartphone = if_else(grepl("p", product_code), 1, 0),
                product_tv = if_else(grepl("v", product_code), 1, 0),
                product_laptop = if_else(grepl("x", product_code), 1, 0),
                product_tablet = if_else(grepl("q", product_code), 1, 0)
                  ) %>% 
            select(-company) %>%
            select(companies, product_category, everything()) 

```

#### Write


```

#### Task 1
Clean Up Brand Names  
```{r}

```

#### Task 2
Separate Product Code and Number  
```{r}

```

#### Task 3
Add Product Categories  
```{r}

```

#### Task 4
Add Full Address for Geocoding  
```{r}

```

#### Task 5
Create Dummy Variables for Company and Product Category  
```{r}

```

